version: "3.7"

services:
  db:
    image: postgres:14
    network_mode: bridge
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:5432

  web:
    build: .
    volumes:
      - $PWD:/app
    ports:
      - 9292:9292
    links:
      - db:db
    depends_on:
      - db
    env_file: .env
    stdin_open: true
    tty: true
    network_mode: bridge
    environment:
      - SESSION_KEY=hak1234
